version: '3.5'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    ports:
      - "9210:9200"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 512M

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5610:5601"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  elasticsearch-volume:
