Args = -H:Name=qalipsis-sample-simple \
    -H:Class=io.qalipsis.runtime.Qalipsis \
    -H:ReflectionConfigurationResources=${.}/reflection-config.json \
    --initialize-at-run-time=\
io.micronaut.http.server.netty.NettyHttpServer,\
io.netty.channel.ChannelHandlerMask,\
io.micronaut.configuration.metrics.micrometer.intercept.TimedInterceptor,\
io.micronaut.aop.chain.InterceptorChain,\
io.micronaut.scheduling.DefaultTaskExceptionHandler,\
io.micronaut.scheduling.io.watch.DefaultWatchThread,\
io.micronaut.context.DefaultBeanContext,\
io.micronaut.http.netty.channel.NettyThreadFactory,\
io.micronaut.runtime.server.watch.event.FileWatchRestartListener,\
io.micronaut.runtime.Micronaut,\
io.micronaut.management.health.monitor.HealthMonitorTask,\
io.micronaut.cache.interceptor.CacheInterceptor,\
io.micronaut.core.io.scan.DefaultClassPathResourceLoader,\
io.micronaut.web.router.AnnotatedMethodRouteBuilder,\
io.micronaut.context.env.DefaultEnvironment,\
io.micronaut.retry.intercept.DefaultRetryInterceptor,\
io.micronaut.context.env.yaml.YamlPropertySourceLoader,\
io.micronaut.scheduling.io.watch.WatchServiceFactory,\
io.micronaut.context.AnnotationProcessorListener,\
io.micronaut.retry.intercept.RecoveryInterceptor,\
io.micronaut.context.DefaultBeanContext,\
io.micronaut.scheduling.processor.ScheduledMethodProcessor,\
io.micronaut.cache.AsyncCacheErrorHandler,\
io.netty.bootstrap.ServerBootstrap,\
io.micronaut.context.DefaultBeanContext,\
io.micronaut.scheduling.executor.DefaultExecutorSelector,\
io.micronaut.management.endpoint.info.source.GitInfoSource,\
io.netty.channel.AbstractChannelHandlerContext,\
io.micronaut.web.router.RouteMatchUtils,\
io.micronaut.management.endpoint.info.source.BuildInfoSource,\
io.micronaut.core.io.scan.ClassPathAnnotationScanner,\
io.micronaut.context,\
io.micronaut.management.health.monitor