# For the executors:
# - 0 or less means the Kotlin Global Scope
# - 1 or more means a fixed thread execution context with the number of threads - cannot be less than 2
# - 1.5x means 1.5 times the number of cores, rounded to the next integer if required - cannot be less than 2
# - name of another executor to reuse it
executors:
  global: 0
  campaign: 2x
  io: 2x
  background: 4
  orchestration: 4

meters:
  export:
    elasticsearch:
      hosts: http://localhost:9200
      enabled: false
      step: 5s
      index: qalipsis-meters
      index-date-format: yyyy-MM-dd

events:
  root: TRACE
  export:
    elasticsearch:
      enabled: false
      urls: http://localhost:9200
      min-level: trace
      store-source: true
      publishers: 1
      batch-size: 30000
    slf4j:
      enabled: true
      min-level: trace

campaign:
  name: distributed-system-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: 50s

http:
  server:
    url: http://localhost:18080
  client:
    pool:
      size: 50

kafka:
  bootstrap: localhost:9093

jdbc:
  url: jdbc:postgresql://localhost:25432/qalipsis
  port: 25432
  database: qalipsis
  username: qalipsis_demo
  password: qalipsis

logging:
  root: WARN
  level:
    io.qalipsis: INFO
    #"io.qalipsis.core.factory.steps.WorkflowStepDecorator": TRACE
    #"io.qalipsis.core.factory.steps.join.InnerJoinStep": TRACE
    #"io.qalipsis.core.factory.orchestration.RunnerImpl": TRACE
    #"io.qalipsis.core.factory.orchestration.FactoryCampaignManagerImpl": TRACE
    #"io.qalipsis.core.factory.orchestration.MinionsKeeperImpl": DEBUG
    #"io.qalipsis.core.factory.orchestration.LocalAssignmentStoreImpl": TRACE
  file:
    async: true
  annotations:
    enabled: false

report:
  export:
    junit:
      enabled: true
      folder: ./build/junit-results
    console:
      enabled: true
