logging:
  console: false
  root: WARN
  level:
    events: TRACE
    io.qalipsis.example: ERROR
    io:
      qalipsis:
        core:
          factories:
            orchestration: ERROR

# For the executors:
# - 0 or less means the Kotlin Global Scope
# - 1 or more means a fixed thread execution context with the number of threads - cannot be less than 2
# - 1.5x means 1.5 times the number of cores, rounded to the next integer if required - cannot be less than 2
# - name of another executor to reuse it
executors:
  global: 0
  campaign: 2x
  io: 2x
  background: 4
  orchestration: 4

meters:
  elasticsearch:
    hosts: http://localhost:9200
    enabled: true
    step: 5s
    index: qalipsis-meters
    index-date-format: yyyy-MM-dd

events:
  root: TRACE
  export:
    elasticsearch:
      enabled: true
      urls: http://localhost:9200
      min-level: trace
      store-source: true
      publishers: 1
      batch-size: 30000
    slf4j:
      enabled: false
      min-level: trace

campaign:
  minions-count-per-scenario: 2000
  minions-factor: 1
  speed-factor: 1
  start-offset-ms: 2000
  name: distributed-system-${random.shortuuid}

http:
  server:
    url: https://localhost:18443
  client:
    pool:
      size: 0

kafka:
  bootstrap: localhost:9093

jdbc:
  url: jdbc:postgresql://localhost:25432/qalipsis
  port: 25432
  database: qalipsis
  username: qalipsis_demo
  password: qalipsis

report:
  export:
    console-live:
      enabled: false