logging:
  console: false
  root: WARN
  level:
    events: TRACE
    io.qalipsis.example: ERROR
    io:
      qalipsis:
        core:
          factories:
            orchestration: ERROR
        plugins:
          r2dbc:
            jasync:
              poll: DEBUG

# For the executors:
# - 0 or less means the Kotlin Global Scope
# - 1 or more means a fixed thread execution context with the number of threads - cannot be less than 2
# - 1.5x means 1.5 times the number of cores, rounded to the next integer if required - cannot be less than 2
# - name of another executor to reuse it
executors:
  global: 0
  campaign: 2x
  io: 2x
  background: 4
  orchestration: 4

meters:
  export:
    enabled: true
    elasticsearch:
      hosts: http://localhost:9200
      enabled: true
      index: qalipsis-meters
      store-source: true
      index-date-format: yyyy-MM-dd
    influxdb:
      url: http://localhost:18086
      enabled: true
      org: qalipsis
      bucket: iot
      prefix: qalipsis
      user-name: qalipsis
      password: qalipsis

events:
  root: TRACE
  export:
    elasticsearch:
      enabled: true
      urls: http://localhost:9200
      min-level: trace
      store-source: true
      publishers: 1
      batch-size: 2000
    influxdb:
      url: http://localhost:18086
      enabled: true
      min-level: trace
      linger-period: 10s
      batch-size: 2000
      publishers: 1
      username: qalipsis
      password: qalipsis
      org: qalipsis
      bucket: iot

    slf4j:
      enabled: false
      min-level: trace

campaign:
  minions-count-per-scenario: 10000
  minions-factor: 1
  speed-factor: 1
  start-offset-ms: 5000
  name: distributed-system-${random.shortuuid}

http:
  server:
    url: https://localhost:18443
  client:
    pool:
      size: 100

kafka:
  bootstrap: localhost:19092

jdbc:
  url: jdbc:postgresql://localhost:25432/qalipsis
  port: 25432
  database: qalipsis
  username: qalipsis_demo
  password: qalipsis

report:
  export:
    console-live:
      enabled: false