services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    volumes:
      - ./docker-config/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro
      - ./docker-config/conf/carbon.conf:/opt/graphite/conf/carbon.conf:ro
    ports:
      - "8080:80"
      - "2003:2003"
      - "2004:2004"
    healthcheck:
      test: nc -z localhost 80
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  healthy_checker:
    container_name: graphite_healthiness_checker
    image: busybox
    depends_on:
      graphite:
        condition: service_healthy