services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./volume/data/:/var/lib/rabbitmq/
      - ./volume/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: qalipsis
      RABBITMQ_DEFAULT_PASS: qalipsis
    healthcheck:
      test: nc -z localhost 5672
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  healthy_checker:
    container_name: rabbitmq_healthiness_checker
    image: busybox
    depends_on:
      rabbitmq:
        condition: service_healthy