campaign:
  name: quickstart-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT2M

logging:
  console: false

report:
  export:
    console-live:
      enabled: false