logging:
  console: true
  root: info
#  level:
#    events: info
#    io.qalipsis.example: info

#meters:
#  elasticsearch:
#    hosts: http://localhost:9210
#    enabled: false
#    step: 5s
#    index: qalipsis-meters
#    index-date-format: yyyy-MM-dd

campaign:
  minions-count-per-scenario: 0
  minions-factor: 1
  speed-factor: 1
  #  start-offset-ms: 500
  name: campaign-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT2M

events:
  root: trace
  export:
    elasticsearch:
      #      enabled: false
      urls: http://localhost:9210
      min-level: trace
      store-source: true
      publishers: 1
      batchSize: 30000
#    slf4j:
#      enabled: false
#      min-level: trace

report:
  export:
    console-live:
      enabled: false