logging:
  console: true
  root: info
  level:
    events: warn
    "events.elasticsearch": debug
    io.qalipsis.example: info

events:
  export:
    slf4j.enabled: true

campaign:
  start-offset-ms: 500
  name: opencellid-import-${random.shortuuid}

micronaut:
  metrics:
    export:
      elastic:
        enabled: false