{ { - if .Values.pgadmin.enabled } }
apiVersion: v1
kind: ConfigMap
metadata:
  name: { { include "qalipsis.fullname" . } }-pgadmin
  labels:
    {{- include "qalipsis.labels" . | nindent 4 }}
    {{- include "qalipsis.selectorLabels" (dict "Release" .Release "component" "pgadmin") | nindent 4 }}
data:
  servers.json: |
    {
      "Servers": {
        "QALIPSIS": {
          "Name": "TimescaleDB",
          "Group": "qalipsis",
          "Host": "{{ include "
          qalipsis.fullname
          " . }}-timescale",
          "Port": {{
      .Values.timescale.service.port}},
    "MaintenanceDB": {{.Values.timescale.postgres.database | quote}},
    "Username": {{.Values.timescale.postgres.user | quote}},
    "SSLMode": "disable"
    }
    }
    }
  { { - end } }
