{ { - if .Values.redis.enabled } }
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "qalipsis.fullname" . } }-redis
  labels:
    {{- include "qalipsis.labels" . | nindent 4 }}
    {{- include "qalipsis.selectorLabels" (dict "Release" .Release "component" "redis") | nindent 4 }}
spec:
  replicas: { { .Values.redis.replicas } }
  selector:
    matchLabels:
      { { - include "qalipsis.selectorLabels" (dict "Release" .Release "component" "redis") | nindent 6 } }
  template:
    metadata:
      labels:
        { { - include "qalipsis.labels" . | nindent 8 } }
          { { - include "qalipsis.selectorLabels" (dict "Release" .Release "component" "redis") | nindent 8 } }
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379
              name: redis
          resources:
            { { - toYaml .Values.redis.resources | nindent 12 } }
          readinessProbe:
            exec:
              command: [ "redis-cli", "ping" ]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 20
          livenessProbe:
            exec:
              command: [ "redis-cli", "ping" ]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
  { { - end } }
