{ { - if .Values.timescale.enabled } }
apiVersion: v1
kind: Secret
metadata:
  name: { { include "qalipsis.fullname" . } }-timescale
  labels:
    {{- include "qalipsis.labels" . | nindent 4 }}
    {{- include "qalipsis.selectorLabels" (dict "Release" .Release "component" "timescale") | nindent 4 }}
type: Opaque
data:
  postgres-password: { { .Values.timescale.postgres.password | b64enc | quote } }
  { { - end } }
