version: '3.9'
services:
  cassandra:
    image: cassandra #https://hub.docker.com/_/cassandra
    container_name: cassandra-server
    restart: always
    environment:
      - CASSANDRA_SNITCH=GossipingPropertyFileSnitch
      - "JVM_OPTS=-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.initial_token=0"
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_DC=qalipsis
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"