version: "3.9"
services:
  influxdb:
    container_name: influxdb-server-container
    image: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: qalipsis_user
      DOCKER_INFLUXDB_INIT_PASSWORD: qalipsis_user_password
      DOCKER_INFLUXDB_INIT_ORG: qalipsis
      DOCKER_INFLUXDB_INIT_BUCKET: iot
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: qalipsis_user_token
    volumes:
      - ./volumes/influxdb2:/var/lib/influxdb2
      - ./volumes/influxdb:/var/lib/influxdb
    ports:
      - "18086:8086"