services:
  influxdb:
    container_name: influxdb-server
    image: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: qalipsis_user
      DOCKER_INFLUXDB_INIT_PASSWORD: qalipsis_user_password
      DOCKER_INFLUXDB_INIT_ORG: qalipsis
      DOCKER_INFLUXDB_INIT_BUCKET: iot
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: qalipsis_user_token
    ports:
      - "18086:8086"
    healthcheck:
      test: curl http://localhost:8086 | grep "InfluxDB is a time series platform"
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  influxdb2:
    container_name: influxdb-server2
    image: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: qalipsis_user
      DOCKER_INFLUXDB_INIT_PASSWORD: qalipsis_user_password
      DOCKER_INFLUXDB_INIT_ORG: qalipsis
      DOCKER_INFLUXDB_INIT_BUCKET: iot
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: qalipsis_user_token
    ports:
      - "18087:8086"
    healthcheck:
      test: curl http://localhost:8086 | grep "InfluxDB is a time series platform"
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  healthy_checker:
    container_name: influxdb_healthiness_checker
    image: busybox
    depends_on:
      influxdb:
        condition: service_healthy
      influxdb2:
        condition: service_healthy