services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: redis-cli --scan --pattern '*' --count 1
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  healthy_checker:
    container_name: redis_healthiness_checker
    image: busybox
    depends_on:
      redis:
        condition: service_healthy
