name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        java: ['11']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1 # https://github.com/actions/setup-java
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-qalipsis-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-qalipsis-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-wrapper-

      - name: Compile
        run: ./gradlew clean build

      - name: Upload JARs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Jars
          path: ./**/build/libs/*-qalipsis.jar
